import React, { Component } from "react";
import { Route, Switch, Redirect } from "react-router-dom";
import NavBar from "./components/navbar";
import Products from "./components/products";
import Posts from "./components/posts";
import Home from "./components/home";
import Dashboard from "./components/admin/dashboard";
import ProductDetails from "./components/productDetails";
import NotFound from "./components/notFound";
import "./App.css";

class App extends Component {
  render() {
    return (
      <div>
        <NavBar />
        <div className="content">
          {/* Route is a component with attributes path and component passed in as props */}
          {/* Route compares the current URL to path. If they match then it renders the component */}
          {/* A <Switch> will iterate over all of its children <Route> elements and only render 
          the first one that matches the current location. */}
          {/* Routes should be ordered from most specific to most generic */}
          {/* Key props of Route are history, loaction and match. These are automatically generated by Route*/}
          {/* History works with the browser to check where the app was previously */}
          {/* Location represents where the app is now */}
          {/* Match contains info about whether the URL matches the path set in the Route */}
          {/* When you want to pass props to the route you use render insted of component. {...props} is used to pass history, match and location */}
          {/* E.g, <Route
              path="/products"
              render={(props) => <Products prop="propToPass" {...props}/>}
            /> */}
          {/* Parameters are passed after the path and prefixed with : A ? marks them as optional*/}
          {/* Redirect is used to send the user to a new destination. 
          It has a from and to parameter. from will be the curremt url and to is the new destination */}
          <Switch>
            <Route path="/products/:id" component={ProductDetails} />
            <Route
              path="/products"
              render={props => <Products sortBy="newest" {...props} />}
            />
            <Route path="/posts/:year?/:month?" component={Posts} />
            <Route path="/admin" component={Dashboard} />
            <Redirect from="/messages" to="/posts" />
            <Route path="/not-found" component={NotFound} />
            <Route path="/" exact component={Home} />
            <Redirect to="/not-found" />
          </Switch>
        </div>
      </div>
    );
  }
}

export default App;
